# Generated by Django 4.2 on 2026-04-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='included_files',
            field=models.TextField(blank=True, help_text='One file or asset per line'),
        ),
        migrations.AddField(
            model_name='project',
            name='information_needed',
            field=models.TextField(blank=True, help_text='Use this space for any missing details still needed'),
        ),
        migrations.AddField(
            model_name='project',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/assets/')),
                ('external_url', models.URLField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.project')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
