# Generated by Django 4.2 on 2026-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_included_files_project_information_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='biggest_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='business_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role_contribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='what_learned',
            field=models.TextField(blank=True),
        ),
    ]
