# Generated by Django 6.0.4 on 2026-04-16 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Creative', 'Creative'), ('Tech', 'Tech'), ('Wellness', 'Wellness'), ('Other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('contact_preference', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('DM', 'Direct message')], max_length=20)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Flexible', 'Flexible')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
